### PR TITLE
Environment changes for all OS

### PR DESCRIPTION
**Pull request by astr0-nat**
added cross-env to the start of 'start' and 'dev' scrips, as well as added nodemon and cross-env to devDependencies in the package.json. Additionally, i renamed .env.test to .env

### CODE REVIEW

**Review by lredmo1 — APPROVED** [review]

**Comment by lredmo1** [comment]
Instead of renaming `.env.test` to `.env`, can you create a new file called `.env` and copy and past the code from `.env.test` into it?

**Comment by astr0-nat** [comment]
I did exactly that in the newest commit :) please let me know if it does not work for anyone, otherwise it would be nice to merge so i dont have to update these files for every pull from main

**Comment by lredmo1** [comment]
> I did exactly that in the newest commit :) please let me know if it does not work for anyone, otherwise it would be nice to merge so i dont have to update these files for every pull from main

LGTM! I think you should be able to merge it? Do we need someone on mac to check on theirs?

**Comment by kasandra0** [comment]
Tested. working on Windows. Merged OS changes

**Pull request merged**
